package org.taurusxi.taurusxicommon.keyValueModel;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig keyValueModelDaoConfig;

    private final KeyValueModelDao keyValueModelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        keyValueModelDaoConfig = daoConfigMap.get(KeyValueModelDao.class).clone();
        keyValueModelDaoConfig.initIdentityScope(type);

        keyValueModelDao = new KeyValueModelDao(keyValueModelDaoConfig, this);

        registerDao(KeyValueModel.class, keyValueModelDao);
    }
    
    public void clear() {
        keyValueModelDaoConfig.getIdentityScope().clear();
    }

    public KeyValueModelDao getKeyValueModelDao() {
        return keyValueModelDao;
    }

}
