package org.taurusxi.taurusxicommon.keyValueModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table KEY_VALUE_MODEL.
 */
public class KeyValueModel {

    /** Not-null value. */
    private String key;
    /** Not-null value. */
    private String value;

    public KeyValueModel() {
    }

    public KeyValueModel(String key) {
        this.key = key;
    }

    public KeyValueModel(String key, String value) {
        this.key = key;
        this.value = value;
    }

    /** Not-null value. */
    public String getKey() {
        return key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String key) {
        this.key = key;
    }

    /** Not-null value. */
    public String getValue() {
        return value;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setValue(String value) {
        this.value = value;
    }

}
